# Site settings
title: Rebecca
header-img: img/home-bg.png
email: reb3cca.fisher@gmail.com
copyright_name: reb3cca
description: > # this means to ignore newlines until "baseurl:"
  Dream. Learn. Build. Repeat.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: /the3nchanting
github_username:  reb3cca
learn_profile: reb3cca
email_username: reb3cca.fisher@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
